#!/usr/bin/perl -p

# convert from img to nested webp/png objects.
# Target image is generated by Pandoc like
#     ![some text][someurl/image.png]\ 
# Condition are:
#   * not a figure
#   * .png image
#   * without text
#   * in article section
#
# WebP image path is simply substituted png to webp.
# You should put samenamed WebP image to same directory as PNG.


if (/<article/ .. /<\/article/) {
  if (m{<p><img src="([^"]+\.png)"(?: alt="([^"]+)")? />[\s ]*</p>}) {
    $pngpath = $1;
    $alttext = $2;
    $webppath = $1;
    $webppath =~ s/\.png$/.webp/;
    $_ = qq{<p><object data="$webppath" type="image/webp"><object data="$pngpath" type="image/png">$alttext</object></object></p>}
  }
}
